Repository purecloudlabs/genesys-cloud-streaming-client, pull requests merged in 2025-07, with the labels that each got.

#305 Stream-643: bump webpack to 5.94.0
  .gitignore
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies

#309 [NO-JIRA] - Revert "Merge pull request #305 from purecloudlabs/STREAM-643"
  .gitignore
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug, dependencies

#308 [STREAM-653] - Added fields to upgradeMediaPresence stanza definition.
  CHANGELOG.md
  package-lock.json
  src/stanza-definitions/webrtc-signaling.ts
  src/webrtc.ts
  test/unit/webrtc.test.ts
Labels: enhancement, dependencies

#306 [STREAM-154] Track StanzaMediaSessions across disconnects
  CHANGELOG.md
  src/webrtc.ts
  test/unit/webrtc.test.ts
Labels: enhancement

#307 [STREAM-155] Calling `disconnect` will stop any in-progress connection attempts
  CHANGELOG.md
  src/client.ts
  src/connection-manager.ts
  src/types/interfaces.ts
  src/types/user-cancelled-error.ts
  test/unit/client.test.ts
Labels: bug-fix, enhancement

#310 [STREAM-652] - Added GitHub Actions for building and running tests.
  .github/actions/cached-deps/action.yml
  .github/workflows/build.yml
  .github/workflows/matrix.yml
  CHANGELOG.md
  scripts/build.ts
Labels: enhancement

#311 release/v19.3.0
  .github/actions/cached-deps/action.yml
  .github/workflows/build.yml
  .github/workflows/matrix.yml
  CHANGELOG.md
  CODEOWNERS
  Jenkinsfile
  README.md
  doc/documentation.md
  package-lock.json
  package.json
  scripts/build.ts
  src/client.ts
  src/connection-manager.ts
  src/connection-transfer.ts
  src/stanza-definitions/webrtc-signaling.ts
  src/stanza-definitions/xep0051.ts
  src/types/interfaces.ts
  src/types/named-agent.ts
  src/types/user-cancelled-error.ts
  src/webrtc.ts
  test/unit/client.test.ts
  test/unit/connection-transfer.test.ts
  test/unit/stanza-definitions/xep0051.test.ts
  test/unit/webrtc.test.ts
Labels: release

#313 [STREAM-801] Update client-logger and axios to fix snyk vuln. Master to dev mergeback.
  .github/workflows/build.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies
